CREATE DATABASE HOSPITAL;
CREATE DATABASE BANK ;
CREATE DATABASE TRANSPORT;
CREATE DATABASE SCHOOL;

DROP DATABASE BANK;

USE SCHOOL;
CREATE TABLE DEPARTMENT(DEPNO VARCHAR(10),DEPNAME VARCHAR(20),DEPLOCATION VARCHAR(20)PRIMARY KEY(DEPNO));
CREATE TABLE COURSE(COURSENO INT,CNAME VARCHAR(20)PRIMARY KEY(COURSENO));

CREATE TABLE STUDENT(STUDID INT,STUDNAME VARCHAR(20),STUDAGE INT,COURSES VARCHAR(20)PRIMARY KEY(STUDID));
CREATE TABLE STAFF(STAFFID INT,STAFFNAME VARCHAR(20),STAFFAGE INT,PRIMARY KEY(STAFFID));

INSERT INTO DEPARTMENT (DEPNO, DEPNAME, DEPLOCATION)
VALUES(1234,'MATHS','MAZRUI');

 INSERT INTO COURSE(COURSENO,CNAME)
 VALUES(01876,'BMCS');


INSERT INTO STUDENT(STUDID ,STUDNAME,STUDAGE,COURSES)
 VALUES(4226642,'RED',34,'BMCS');



 INSERT INTO STAFF(STAFFID,STAFFNAME,STAFFAGE)
 VALUES(01208,'FRED',50);

INSERT INTO DEPARTMENT (DEPNO, DEPNAME, DEPLOCATION)
VALUES(923124,'MATHS','MAZRUI');

 INSERT INTO COURSE(COURSENO,CNAME)
 VALUES(09876,'BMCS');


INSERT INTO STUDENT(STUDID ,STUDNAME,STUDAGE,COURSES)
 VALUES(46642,'RED',34,'BMCS');

 INSERT INTO STAFF(STAFFID,STAFFNAME,STAFFAGE)
 VALUES(0204298,'OMOGI',520);

INSERT INTO DEPARTMENT (DEPNO, DEPNAME, DEPLOCATION)
VALUES(1284238,'PHYS','M-BLOCK');

 INSERT INTO COURSE(COURSENO,CNAME)
 VALUES(08249231,'BSMF');


INSERT INTO STUDENT(STUDID ,STUDNAME,STUDAGE,COURSES)
 VALUES(4624142,'ROY',34,'BTCS');

 INSERT INTO STAFF(STAFFID,STAFFNAME,STAFFAGE)
 VALUES(492788808,'REGGIE',530);


INSERT INTO DEPARTMENT (DEPNO, DEPNAME, DEPLOCATION)
VALUES(1328944,'MATHS','MAUA');

 INSERT INTO COURSE(COURSENO,CNAME)
 VALUES(898948776,'BMCS');


INSERT INTO STUDENT(STUDID ,STUDNAME,STUDAGE,COURSES)
 VALUES(46481642,'RED',34,'BMCS');

 INSERT INTO STAFF(STAFFID,STAFFNAME,STAFFAGE)
 VALUES(0483208,'FRED',50);

 SELECT STUDID FROM STUDENT;
SELECT *FROM DEPARTMENT;
 SELECT CNAME FROM COURSE;

  SELECT STAFFNAME, STAFFAGE FROM STAFF;

